### ISSUE TITLE
v3.0 js bug

### ISSUE THREAD

**Issue by 87439247** [fagongzi/gateway-ui-vue#10]
app.4d269715.js:1 Uncaught TypeError: Cannot read property 'zh' of undefined
    at Module.Vtdi (app.4d269715.js:1)
    at h ((index):4)
    at c ((index):4)
    at Array.n [as push] ((index):4)
    at app.4d269715.js:1

v3.0

**Comment by bosscheng** [comment]
@87439247 做什么操作出现的？这边无法复现这个问题。

**Comment by 87439247** [comment]
3.0.0分支 最新版本, 在npm run build 的时候
WARNING in ./src/lang/index.js 21:39-52
"export 'LANGUAGE_TYPE' was not found in '~/constant/constant'
 @ ./src/main.js

WARNING in ./src/store/modules/app.js 21:45-58
"export 'LANGUAGE_TYPE' was not found in '~/constant/constant'
 @ ./src/store/index.js
 @ ./src/main.js

运行的时候, 就报了上面的js错误

**Comment by 87439247** [comment]
index.vue 大小写有问题
  this.routingNum = count.Routing || 0;
  this.routingNum = count.routing || 0;

**Comment by bosscheng** [comment]
@87439247 发现了，合并代码的时候，出现了遗漏，谢谢！

**Comment by bosscheng** [comment]
修复，提交上去了。
