### ISSUE TITLE
数据缓存模块获取PathValue时提示的index设置错误

### ISSUE THREAD

**Issue by caozhipan** [fagongzi/gateway-ui-vue#7]
在数据缓存模块，当设置匹配规则或者关键词为PathValue时，提示
`http://example.com/path1/path2/path3?xxx=aa,填写1匹配path1，2匹配path2，3匹配path3`

gateway中取PathValue时使用的代码：
`
func getPathValue(idx int, req *fasthttp.Request) string {
	path := hack.SliceToString(req.URI().Path()[1:])
	values := strings.Split(path, "/")
	if len(values) <= idx {
		return ""
	}

	return values[idx]
}
`
可知index起始位置不一致

**建议修改提示文案为**
`http://example.com/path0/path1/path2?xxx=aa,填写0匹配path0，1匹配path1，2匹配path2`

**Comment by bosscheng** [comment]
这个问题不属于ui 项目的，应该去fagongzi/gateway 项目提。https://github.com/fagongzi/gateway
